 # deployment.yml
 kind:       Deployment
 apiVersion: extensions/v1beta1
 metadata:
   name: registry
   labels:
     app: registry
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: registry
     spec:
       containers:
         - name:  registry
           image: docker.io/registry:2
           ports:
             - containerPort: 5000
               name:          client